### DISCUSSION TITLE
the camtrap datapackage extension

### DISCUSSION THREAD

**Discussion by pvgenuchten** [soilwise-he/soil-observation-data-encodings#22] [Ideas]
[the camtrap extension](https://camtrap-dp.tdwg.org/) is referenced from the [main datapackage documentation](https://datapackage.org/standard/extensions/), it is of interest because it proposes a set of conventions within an existing de-facto standard. EUSO/SWR could propose a similar convention, `SoilObservations datapackage extension`, which could facilitate the sharing of soil observation data, it has much similarities with how soil data is typically exchanged these days. This would be an alternative to the SoilGeoPackage approach which is suggested by EJP.

the extension would define a set of tabular datasets (in either csv, excel, access format) with their metadata

```mermaid
flowchart TD

    SP[SoilObservations] --> A[Sites]
    A --> AO[Site observations]
    SP --> B[Profiles]
    B --> BO[Profile observations]
    SP --> C[Layers]
    C --> CO[Layer observations]
```

The datapackage conventions facilitate the capture of unit, procedure as part of the column metadata (as long as the unit and procedure do not vary within a single datapackage)

The Layer observations table for example looks like:

| Layer | Date | Surveyer | Ca | Mg | Sand | Silt | Clay | 
| --- | --- | --- | --- | --- | --- | --- | --- | 
| AO3257-15-A | 2024-05-21 | Jenssen | .81 | .22 | .33 | .33 | .33 |
| AO3257-15-B | 2024-05-21 | Jenssen | .94 | .34 | .20 | .40 | .40 |

And its metadata

```yaml
fields:
   Layer
      type: String
      description: the identification of a layer in a profile
   Date:
      type: Date
      description: Date the samples were taken
   Surveyor:
      type: String
      description: Name of the field surveyor
   Ca:
      type: Double
      title: Calcium content   
      description: shaking a 1-gram scoop of air-dried soil with 10 milliliters of 1 N (pH7) ammonium acetate (NH4OAc) for 5 minutes
      unit: g/g
   Mg:
      type: Double
      title: Magnesium content   
      description: shaking a 1-gram scoop of air-dried soil with 10 milliliters of 1 N (pH7) ammonium acetate (NH4OAc) for 5 minutes
      unit: g/g
   Sand: 
      type: Double
      title: Sand content   
      description: Winnowing 
      unit: g/g
   Silt:
      type: Double
      title: Silt content   
      description: Winnowing 
      unit: g/g
   Clay:
      type: Double
      title: Clay content   
      description: Winnowing 
      unit: g/g
```
